version: '3'

services:
  mongodb: 
    image: mongo:latest
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - mongodb:/data/db

  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongodb

volumes:
  mongodb:
    
    
